services:
  jms_grafana:
    container_name: jms_grafana 
    image: grafana/grafana:latest
    env_file: ./envs/.env.grafana
    ports:
      - "3300:3000"
    volumes:
      - ./volumes/grafana/provisioning:/etc/grafana/provisioning
      - jms_grafana_volume:/var/lib/grafana
    networks:
      - jms_network
    restart: unless-stopped

volumes:
  jms_grafana_volume:
    name: jms_grafana_volume
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./volumes/grafana/data