services:
  rabbitmq:
    image: rabbitmq:4.1.0-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - rabbitmq_volume:/var/lib/rabbitmq
    ulimits:
      nofile:
        soft: 65535
        hard: 65535

volumes:
  rabbitmq_volume:
    name: rabbitmq_volume
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./volumes/rabbitmq