services:
  jms_rabbitmq:
    image: rabbitmq:4.1.0-management-alpine
    container_name: jms_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - envs/.env.rabbitmq
    networks:
      - jms_network
    restart: unless-stopped
    volumes:
      - jms_rabbitmq_volume:/var/lib/rabbitmq

volumes:
  jms_rabbitmq_volume:
    name: jms_rabbitmq_volume
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./volumes/rabbitmq