# Settings specific ONLY to the Background Consumer worker node
server:
  port: -1

spring:
  liquibase:
    enabled: false

  rabbitmq:
    listener:
      simple:
        default-requeue-rejected: false
        concurrency: ${RABBITMQ_LISTENER_CONCURRENCY:20}
        max-concurrency: ${RABBITMQ_LISTENER_MAX_CONCURRENCY:20}
        prefetch: ${RABBITMQ_LISTENER_PREFETCH:20}
        acknowledge-mode: auto