app:
  backend-url: ${BACKEND_URL}

spring:
  application:
    name: api

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml

  jpa:
    hibernate:
      ddl-auto: none

    show-sql: false

    properties:
      hibernate:
        jdbc:
          batch_size: 50
          order_inserts: true
          order_updates: true

    database-platform: org.hibernate.dialect.PostgreSQLDialect


  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

    listener:
      simple:
        default-requeue-rejected: false
        concurrency: 20
        max-concurrency: 20
        prefetch: 20
        acknowledge-mode: auto


logging:
  level:
    root: INFO

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n"


jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}